import type {
  Assessment,
  Course,
  LearningPath,
  Skill,
  UserProfile,
} from '@/types';

export const mockUser: UserProfile = {
  name: 'Maya',
  avatarInitials: 'MK',
  careerGoal: 'Senior Frontend Engineer',
  interests: ['React', 'TypeScript', 'System Design', 'Accessibility'],
  weeklyHours: 12,
  streak: 23,
  longestStreak: 41,
  overallProgress: 64,
  activeDays: [1, 2, 3, 5, 6, 8, 9, 10, 12, 14, 15, 16, 17, 19, 20, 21],
  prevMonthActiveDays: [2, 4, 5, 7, 8, 11, 13, 14, 18, 20, 22, 25, 27, 28],
  nextMonthActiveDays: [],
};

export const mockSkills: Skill[] = [
  {
    id: 'react',
    name: 'React',
    icon: 'Atom',
    current: 78,
    target: 90,
    targetLabel: 'Senior',
    level: 'Advanced',
    mastered: false,
    nextMilestone: 'Complete Advanced React Patterns to reach 85',
    domain: 'Web Dev',
  },
  {
    id: 'typescript',
    name: 'TypeScript',
    icon: 'FileCode2',
    current: 82,
    target: 88,
    targetLabel: 'Senior',
    level: 'Advanced',
    mastered: false,
    nextMilestone: 'Finish Generics Deep-Dive to reach 86',
    domain: 'Web Dev',
  },
  {
    id: 'testing',
    name: 'Testing',
    icon: 'FlaskConical',
    current: 54,
    target: 80,
    targetLabel: 'Senior',
    level: 'Intermediate',
    mastered: false,
    nextMilestone: 'Pass the Testing Strategies quiz to reach 62',
    domain: 'Web Dev',
  },
  {
    id: 'system-design',
    name: 'System Design',
    icon: 'Network',
    current: 41,
    target: 75,
    targetLabel: 'Senior',
    level: 'Intermediate',
    mastered: false,
    nextMilestone: 'Complete Frontend Architecture module to reach 50',
    domain: 'Web Dev',
  },
  {
    id: 'accessibility',
    name: 'Accessibility',
    icon: 'Accessibility',
    current: 67,
    target: 78,
    targetLabel: 'Senior',
    level: 'Intermediate',
    mastered: false,
    nextMilestone: 'Read ARIA Patterns Guide to reach 72',
    domain: 'Web Dev',
  },
  {
    id: 'css',
    name: 'CSS & Layout',
    icon: 'Palette',
    current: 92,
    target: 85,
    targetLabel: 'Senior',
    level: 'Expert',
    mastered: true,
    nextMilestone: 'Mastered — maintaining through practice',
    domain: 'Web Dev',
  },
  {
    id: 'performance',
    name: 'Performance',
    icon: 'Gauge',
    current: 58,
    target: 80,
    targetLabel: 'Senior',
    level: 'Intermediate',
    mastered: false,
    nextMilestone: 'Complete Web Vitals lab to reach 66',
    domain: 'Web Dev',
  },
  {
    id: 'dsa',
    name: 'Data Structures',
    icon: 'Binary',
    current: 48,
    target: 70,
    targetLabel: 'Senior',
    level: 'Intermediate',
    mastered: false,
    nextMilestone: 'Solve 5 medium tree problems to reach 55',
    domain: 'DSA',
  },
];

export const mockCourses: Course[] = [
  {
    id: 'c1',
    title: 'Advanced React Patterns',
    description: 'Compound components, render props, and headless hooks for building flexible, reusable UI libraries.',
    icon: 'Atom',
    subject: 'React',
    subjectColor: 'amber',
    resourceType: 'course',
    status: 'in-progress',
    progress: 62,
    prerequisites: ['React fundamentals', 'Hooks basics'],
    whyRecommended: 'Core to your Senior Frontend goal — directly closes the patterns gap in your React skill.',
    pathId: 'p1',
    durationHours: 14,
    bookmarked: true,
  },
  {
    id: 'c2',
    title: 'TypeScript Generics Deep-Dive',
    description: 'Master conditional types, inference, and mapped types to write type-safe libraries and APIs.',
    icon: 'FileCode2',
    subject: 'TypeScript',
    subjectColor: 'iris',
    resourceType: 'course',
    status: 'in-progress',
    progress: 35,
    prerequisites: ['TypeScript basics'],
    whyRecommended: 'Your TS level is strong but generics are the ceiling-buster for senior roles.',
    pathId: 'p1',
    durationHours: 9,
    bookmarked: false,
  },
  {
    id: 'c3',
    title: 'Testing Strategies for React',
    description: 'Component testing, integration tests, and confidence-driven testing philosophy with Vitest and RTL.',
    icon: 'FlaskConical',
    subject: 'Testing',
    subjectColor: 'sage',
    resourceType: 'course',
    status: 'in-progress',
    progress: 20,
    prerequisites: ['React fundamentals'],
    whyRecommended: 'Testing is your widest skill gap (54 → 80). This course is the fastest path to close it.',
    pathId: 'p1',
    durationHours: 11,
    bookmarked: false,
  },
  {
    id: 'c4',
    title: 'Build a Design System',
    description: 'A hands-on project: ship a themeable component library with tokens, docs, and Storybook.',
    icon: 'Layers',
    subject: 'React',
    subjectColor: 'amber',
    resourceType: 'project',
    status: 'recommended',
    progress: 0,
    prerequisites: ['Advanced React Patterns'],
    whyRecommended: 'Projects demonstrate senior-level component architecture and token systems.',
    pathId: 'p1',
    durationHours: 20,
    bookmarked: true,
  },
  {
    id: 'c5',
    title: 'Frontend Accessibility Patterns',
    description: 'ARIA, focus management, and semantic HTML patterns for building inclusive interfaces.',
    icon: 'Accessibility',
    subject: 'Accessibility',
    subjectColor: 'iris',
    resourceType: 'article',
    status: 'completed',
    progress: 100,
    prerequisites: ['HTML basics'],
    whyRecommended: 'Reinforces your accessibility skill toward the senior target.',
    pathId: 'p1',
    durationHours: 4,
    bookmarked: false,
  },
  {
    id: 'c6',
    title: 'Web Vitals Performance Lab',
    description: 'Measure and optimize LCP, CLS, and INP with real-world techniques and Chrome tooling.',
    icon: 'Gauge',
    subject: 'Performance',
    subjectColor: 'amber',
    resourceType: 'course',
    status: 'recommended',
    progress: 0,
    prerequisites: ['Browser rendering basics'],
    whyRecommended: 'Performance is a measured gap and a common senior interview topic.',
    pathId: 'p2',
    durationHours: 8,
    bookmarked: false,
  },
  {
    id: 'c7',
    title: 'System Design for Frontend',
    description: 'Architecting state, data flow, and rendering strategies at scale.',
    icon: 'Network',
    subject: 'Architecture',
    subjectColor: 'iris',
    resourceType: 'course',
    status: 'in-progress',
    progress: 48,
    prerequisites: ['React fundamentals', 'State management basics'],
    whyRecommended: 'Frontend system design is increasingly tested in senior loops.',
    pathId: 'p2',
    durationHours: 16,
    bookmarked: false,
  },
  {
    id: 'c8',
    title: 'Tree Problems Mastery',
    description: 'BFS, DFS, BST operations, and common interview patterns with trees.',
    icon: 'Binary',
    subject: 'DSA',
    subjectColor: 'iris',
    resourceType: 'quiz',
    status: 'recommended',
    progress: 0,
    prerequisites: ['Recursion basics'],
    whyRecommended: 'DSA is a gap and trees are your weakest data structure.',
    pathId: 'p3',
    durationHours: 6,
    bookmarked: false,
  },
  {
    id: 'c9',
    title: 'CSS Grid & Subgrid',
    description: 'Modern layout techniques for complex, responsive page structures.',
    icon: 'Palette',
    subject: 'CSS',
    subjectColor: 'amber',
    resourceType: 'article',
    status: 'completed',
    progress: 100,
    prerequisites: ['Flexbox basics'],
    whyRecommended: 'Keeps your already-mastered CSS skill sharp.',
    pathId: 'p4',
    durationHours: 3,
    bookmarked: false,
  },
];

export const mockPaths: LearningPath[] = [
  {
    id: 'p1',
    title: 'Senior Frontend Engineer Track',
    subtitle: 'React architecture, testing, and team-level patterns',
    domain: 'Web Dev',
    type: 'career',
    difficulty: 'Advanced',
    stageCount: 6,
    durationWeeks: 24,
    color: 'amber',
    active: true,
    stages: [
      {
        id: 's1',
        index: 1,
        title: 'React Patterns Core',
        description: 'Compound components, hooks composition, and headless UI patterns.',
        status: 'completed',
        durationWeeks: 4,
        milestones: ['Build a headless accordion', 'Ship a compound form component'],
        prerequisites: ['React fundamentals'],
        why: 'Patterns are the vocabulary of senior React work — everything later builds on this.',
        skillIds: ['react'],
      },
      {
        id: 's2',
        index: 2,
        title: 'TypeScript for Libraries',
        description: 'Generics, conditional types, and type-safe API design.',
        status: 'active',
        durationWeeks: 3,
        milestones: ['Type a generic useFetch hook', 'Publish a typed utility package'],
        prerequisites: ['React Patterns Core'],
        why: 'Senior roles expect you to design types that guide other engineers safely.',
        skillIds: ['typescript'],
      },
      {
        id: 's3',
        index: 3,
        title: 'Testing Strategies',
        description: 'Component, integration, and confidence-driven testing.',
        status: 'upcoming',
        durationWeeks: 4,
        milestones: ['Reach 80% coverage on a feature', 'Write an integration test suite'],
        prerequisites: ['TypeScript for Libraries'],
        why: 'Testing confidence is the single biggest gap in your profile toward senior.',
        skillIds: ['testing'],
      },
      {
        id: 's4',
        index: 4,
        title: 'Frontend Architecture',
        description: 'State, data flow, and rendering strategy at scale.',
        status: 'locked',
        durationWeeks: 5,
        milestones: ['Design a state architecture doc', 'Refactor a legacy feature'],
        prerequisites: ['Testing Strategies'],
        why: 'System design on the frontend is where mid and senior diverge clearly.',
        skillIds: ['system-design'],
      },
      {
        id: 's5',
        index: 5,
        title: 'Performance & Accessibility',
        description: 'Web vitals, inclusive patterns, and measurement.',
        status: 'locked',
        durationWeeks: 4,
        milestones: ['Hit Good Core Web Vitals on a page', 'Pass an axe audit clean'],
        prerequisites: ['Frontend Architecture'],
        why: 'Performance and accessibility are non-negotiable senior responsibilities.',
        skillIds: ['performance', 'accessibility'],
      },
      {
        id: 's6',
        index: 6,
        title: 'Team Leadership Capstone',
        description: 'Design system, code review culture, and mentoring.',
        status: 'locked',
        durationWeeks: 4,
        milestones: ['Ship a design system v1', 'Lead a code review workshop'],
        prerequisites: ['Performance & Accessibility'],
        why: 'Senior is a leadership track — this stage proves you can elevate a team.',
        skillIds: ['react', 'css'],
      },
    ],
  },
  {
    id: 'p2',
    title: 'Frontend Performance Engineering',
    subtitle: 'Measure, diagnose, and optimize real-world web apps',
    domain: 'Web Dev',
    type: 'skill',
    difficulty: 'Intermediate',
    stageCount: 4,
    durationWeeks: 12,
    color: 'amber',
    active: false,
    stages: [],
  },
  {
    id: 'p3',
    title: 'DSA Interview Sprint',
    subtitle: 'Trees, graphs, DP, and patterns for frontend interviews',
    domain: 'DSA',
    type: 'interview',
    difficulty: 'Intermediate',
    stageCount: 5,
    durationWeeks: 8,
    color: 'iris',
    active: false,
    stages: [],
  },
  {
    id: 'p4',
    title: 'Modern CSS Foundations',
    subtitle: 'Grid, container queries, and design tokens',
    domain: 'Web Dev',
    type: 'beginner',
    difficulty: 'Beginner',
    stageCount: 3,
    durationWeeks: 6,
    color: 'sage',
    active: false,
    stages: [],
  },
  {
    id: 'p5',
    title: 'Cloud-Native Frontend',
    subtitle: 'Edge rendering, CDNs, and serverless UI delivery',
    domain: 'Cloud',
    type: 'career',
    difficulty: 'Advanced',
    stageCount: 4,
    durationWeeks: 14,
    color: 'iris',
    active: false,
    stages: [],
  },
];

export const mockAssessments: Assessment[] = [
  {
    id: 'a1',
    title: 'React Patterns Checkpoint',
    description: 'Validate your understanding of compound components and headless hooks.',
    pathId: 'p1',
    pathTitle: 'Senior Frontend Engineer Track',
    stageId: 's1',
    status: 'passed',
    questionCount: 4,
    estMinutes: 6,
    skillId: 'react',
    questions: [
      {
        id: 'q1',
        prompt: 'Which pattern lets you compose components without prop drilling through a shared context?',
        options: ['Render props', 'Compound components', 'Higher-order components', 'Memoization'],
        correctIndex: 1,
        explanation: 'Compound components share context implicitly, so children get state without prop drilling.',
      },
      {
        id: 'q2',
        prompt: 'A headless hook primarily provides:',
        options: ['Pre-styled UI', 'State and logic without markup', 'Animation utilities', 'Routing helpers'],
        correctIndex: 1,
        explanation: 'Headless hooks return state and handlers, leaving the markup entirely to the consumer.',
      },
      {
        id: 'q3',
        prompt: 'Which is a downside of render props versus hooks?',
        options: ['No access to state', 'Can cause wrapper hell and re-renders', 'Cannot be typed', 'Requires context'],
        correctIndex: 1,
        explanation: 'Deeply nested render props create wrapper hell and can trigger wider re-renders.',
      },
      {
        id: 'q4',
        prompt: 'useId is best used for:',
        options: ['List keys', 'Stable accessibility IDs', 'Animation triggers', 'Data fetching'],
        correctIndex: 1,
        explanation: 'useId generates stable, hydration-safe IDs ideal for label/input aria associations.',
      },
    ],
  },
  {
    id: 'a2',
    title: 'TypeScript Generics Quiz',
    description: 'Test conditional types, inference, and mapped type knowledge.',
    pathId: 'p1',
    pathTitle: 'Senior Frontend Engineer Track',
    stageId: 's2',
    status: 'needs-review',
    questionCount: 4,
    estMinutes: 5,
    skillId: 'typescript',
    questions: [
      {
        id: 'q1',
        prompt: 'What does `T extends U ? X : Y` express?',
        options: ['A loop over T', 'A conditional type', 'A mapped type', 'A utility type'],
        correctIndex: 1,
        explanation: 'Conditional types branch the resulting type based on a constraint check.',
      },
      {
        id: 'q2',
        prompt: 'infer is used to:',
        options: ['Declare a variable', 'Extract a type from another type', 'Validate runtime values', 'Import types'],
        correctIndex: 1,
        explanation: 'infer captures a sub-type within a conditional type, e.g. function return types.',
      },
      {
        id: 'q3',
        prompt: 'A mapped type { [K in keyof T]: ... } produces:',
        options: ['A union', 'A new object type transforming T', 'A tuple', 'An enum'],
        correctIndex: 1,
        explanation: 'Mapped types iterate over keys of T to produce a transformed object type.',
      },
      {
        id: 'q4',
        prompt: 'Which utility makes all properties of T readonly?',
        options: ['Required<T>', 'Readonly<T>', 'Partial<T>', 'Pick<T>'],
        correctIndex: 1,
        explanation: 'Readonly<T> maps every property to readonly, preventing reassignment.',
      },
    ],
  },
  {
    id: 'a3',
    title: 'Testing Strategies Quiz',
    description: 'Validate your understanding of confidence-driven testing.',
    pathId: 'p1',
    pathTitle: 'Senior Frontend Engineer Track',
    stageId: 's3',
    status: 'not-started',
    questionCount: 4,
    estMinutes: 5,
    skillId: 'testing',
    questions: [
      {
        id: 'q1',
        prompt: 'The testing trophy recommends focusing most on:',
        options: ['Unit tests', 'Integration tests', 'End-to-end tests', 'Static analysis'],
        correctIndex: 1,
        explanation: 'Integration tests give the best confidence-to-effort ratio in the trophy model.',
      },
      {
        id: 'q2',
        prompt: 'RTL queries by accessible name use:',
        options: ['getByRole', 'getByTestId', 'querySelector', 'getByClass'],
        correctIndex: 0,
        explanation: 'getByRole with a name option queries how assistive tech sees the element.',
      },
      {
        id: 'q3',
        prompt: 'A flaky test usually indicates:',
        options: ['A bug in the test framework', 'Hidden shared state or timing issues', 'Too few assertions', 'Slow CI'],
        correctIndex: 1,
        explanation: 'Flakiness almost always traces to uncontrolled state, time, or async ordering.',
      },
      {
        id: 'q4',
        prompt: 'Which is a symptom of testing implementation details?',
        options: ['Tests break on refactors with no behavior change', 'Tests run fast', 'Tests use getByRole', 'Tests pass in CI'],
        correctIndex: 0,
        explanation: 'Implementation-coupled tests break when internals change even if behavior is identical.',
      },
    ],
  },
  {
    id: 'a4',
    title: 'Frontend Architecture Checkpoint',
    description: 'System design for state, data flow, and rendering strategy.',
    pathId: 'p2',
    pathTitle: 'Frontend Performance Engineering',
    stageId: 's4',
    status: 'not-started',
    questionCount: 4,
    estMinutes: 7,
    skillId: 'system-design',
    questions: [
      {
        id: 'q1',
        prompt: 'Colocating state near where it is used primarily improves:',
        options: ['Bundle size', 'Maintainability and re-render scope', 'SEO', 'Compile speed'],
        correctIndex: 1,
        explanation: 'Colocation narrows re-render scope and keeps logic near its consumers.',
      },
      {
        id: 'q2',
        prompt: 'For a dashboard with live data, a good default rendering strategy is:',
        options: ['Static generation', 'Incremental static regeneration with client updates', 'Full client SPA', 'SSR every request'],
        correctIndex: 1,
        explanation: 'ISR gives a fast initial paint and lets client-side updates layer in live data.',
      },
      {
        id: 'q3',
        prompt: 'A render budget on the main thread is best monitored with:',
        options: ['console.time', 'Performance Observer + Long Task API', 'Lighthouse CI only', 'Network tab'],
        correctIndex: 1,
        explanation: 'Performance Observer surfaces long tasks that blow the 50ms interaction budget.',
      },
      {
        id: 'q4',
        prompt: 'When should you introduce a global state library?',
        options: ['Always, for safety', 'When prop drilling is real and frequent', 'Never', 'Only for forms'],
        correctIndex: 1,
        explanation: 'Add global state only when prop drilling is genuinely painful — not preemptively.',
      },
    ],
  },
];

export const chatQuickSuggestions = [
  'What are my skill gaps?',
  'Show my roadmap',
  'Re-rank my path',
  'I am better at Testing than that',
];

export const courseTopicFilters = [
  { id: 'all', label: 'All', icon: 'LayoutGrid' },
  { id: 'React', label: 'React', icon: 'Atom' },
  { id: 'TypeScript', label: 'TypeScript', icon: 'FileCode2' },
  { id: 'Testing', label: 'Testing', icon: 'FlaskConical' },
  { id: 'Architecture', label: 'Architecture', icon: 'Network' },
  { id: 'Performance', label: 'Performance', icon: 'Gauge' },
  { id: 'Accessibility', label: 'Accessibility', icon: 'Accessibility' },
  { id: 'DSA', label: 'DSA', icon: 'Binary' },
  { id: 'CSS', label: 'CSS', icon: 'Palette' },
];

export const pathDomainFilters = [
  { id: 'all', label: 'All', icon: 'LayoutGrid' },
  { id: 'Web Dev', label: 'Web Dev', icon: 'Code2' },
  { id: 'Data Science', label: 'Data Science', icon: 'BarChart3' },
  { id: 'DSA', label: 'DSA', icon: 'Binary' },
  { id: 'Cloud', label: 'Cloud', icon: 'Cloud' },
];
